### ISSUE TITLE
很多功能还没有，希望官方尽快完善

### ISSUE THREAD

**Issue by extreme-w** [bmob/bmob-flutter-sdk#5]
比如：分页查询、统计对象数量，已经在用SDK，感觉还不错，希望官方尽快完善，O(∩_∩)O

**Comment by chaozhouzhang** [comment]
分页查询已经新增，更多功能也会陆续完善，感谢关注并提建议，O(∩_∩)O

**Comment by extreme-w** [comment]
0.0.8不完善的地方：
BmobQuery<Post> query = BmobQuery();
    query.setLimit(10);//如果不加这行，查询结果为空
    query.queryObjects(successListener: (List<dynamic> data) {
      if(data.isEmpty){
        print('为空');
      }else{
        print('不为空');
      }
    }, errorListener: (error) {
      print(error.error);
    });

**Comment by chaozhouzhang** [comment]
> 0.0.8不完善的地方：
> BmobQuery query = BmobQuery();
> query.setLimit(10);//如果不加这行，查询结果为空
> query.queryObjects(successListener: (List data) {
> if(data.isEmpty){
> print('为空');
> }else{
> print('不为空');
> }
> }, errorListener: (error) {
> print(error.error);
> });

你好，此bug已经修复，请使用v0.0.9版本。
